name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
  pull_request:
  schedule:
    - cron: '5/0 * * * *'


jobs:
  check-bats-version:
    # runs-on: ubuntu-latest
    if: github.event_name == 'push'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
        # with:
          # node-version: '14'
      # - run: npm install -g bats
      # - run: bats -v
      - run: export
      - run: pwd
      - run: ls ./
      - run: ls ../
      - run: ls ../../
      - run: ls ../../../
      - run: echo "this is a test" > ./ci_gen1.txt


  test_schedule:
    if: github.event_name == 'schedule'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: echo "test ci scheduler"
      - run: echo github.event.schedule